import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Profile } from '@/components/Profile/Profile'
import { About } from '@/components/About/About'
import { Experience } from '@/components/Experience/Experience'
import { Contact } from '@/components/Contact/Contact'
import { FName } from '@/components/FName/FName'
import JobGrid from '@/components/JobGrid/JobGrid'
import Navbar from '@/components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Víctor Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <FName/>
      <main className={styles.main}>
      <Profile/>
      <JobGrid/>
      <About/>
      <Experience/>
      <Contact/>
        
      </main>
    </>
  )
}
